FROM golang:1.26.1-alpine

ENV GO111MODULE=on CGO_ENABLED=0 GOEXPERIMENT=greenteagc
ENV PATH="/go/bin:${PATH}"

WORKDIR /app

RUN apk add --no-cache ca-certificates git tzdata wget \
    && go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
